### ISSUE TITLE
Mismatched glow on Leaderboards

### ISSUE THREAD

**Issue by Aktimoose** [sofabeddd/Colored-Icon-Kit#1]
On the leaderboards, the glow colour for anyone with glow enabled will match whatever mine is.
![image](https://github.com/sofabeddd/Colored-Icon-Kit/assets/44620677/3c28ff1c-a93e-40c6-9930-8aa21c63a1cd)
![image](https://github.com/sofabeddd/Colored-Icon-Kit/assets/44620677/326a1131-cd09-4ffe-9ae7-ad87d7a0773c)

This is also the case in level comment sections
![image](https://github.com/sofabeddd/Colored-Icon-Kit/assets/44620677/8d4bc1f6-6e10-4436-8e47-a33b0c95fdda)

Mod Version v1.0.0
Geode Version v2.0.0-beta.20

**Comment by sofabeddd** [comment]
comments cant be fixed as far as ive tested but i will try to fix leaderboards

**Comment by sofabeddd** [comment]
should be fixed in v1.0.1 now

**Comment by shroomsnjunk** [comment]
Comment icons still have my glow color with v1.0.2 installed, not sure why...
