### ISSUE TITLE
glow still showing even if yoy have it off

### ISSUE THREAD

**Issue by imCocoa** [sofabeddd/Colored-Icon-Kit#2]
glow color still shows of the icons even if youve turned it off
![Screenshot_20240223-143143](https://github.com/sofabeddd/Colored-Icon-Kit/assets/160286628/62d4fb29-d0cf-4aa9-8329-f421a3d7f090)
![Screenshot_20240223-143148](https://github.com/sofabeddd/Colored-Icon-Kit/assets/160286628/effcee8d-c563-4059-8ce9-a96a0e3bb834)

**Comment by imCocoa** [comment]
on mobile btw

**Comment by sofabeddd** [comment]
is fixed in v1.0.5
