### ISSUE TITLE
I made an icon for this mod if you want to use it!

### ISSUE THREAD

**Issue by RueOfficial** [sofabeddd/Colored-Icon-Kit#3]
![ColoredIcon](https://github.com/sofabeddd/Colored-Icon-Kit/assets/60704088/9f98cc3b-e812-4176-801e-544b192edc4b)

**Comment by RueOfficial** [comment]
Here is how it would look like in-game
![image](https://github.com/sofabeddd/Colored-Icon-Kit/assets/60704088/18e4f3f5-e226-41c8-8f33-45b7a64902c4)
![image](https://github.com/sofabeddd/Colored-Icon-Kit/assets/60704088/20c3c513-7808-4c8e-8821-1156cb831a58)

**Comment by sofabeddd** [comment]
this is epic, dm me on discord i got a few changes if you dont mind

**Comment by RueOfficial** [comment]
Sure thing
