### ISSUE TITLE
Issue  with colored icon sets

### ISSUE THREAD

**Issue by sk11taddle** [sofabeddd/Colored-Icon-Kit#5]
I just opened up the customization area or garage, whatever its called, and all of the colors were wrong, unless this is an april fools thing.
![20240401120132_1](https://github.com/sofabeddd/Colored-Icon-Kit/assets/165699152/62629d98-e29e-4def-a527-43fcd3aea63a)

**Comment by sofabeddd** [comment]
oh this bug will be fixed april 2nd
